# Generated by Django 2.2.1 on 2020-01-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ContactModel',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
